export const styles = {
  container: ["bg-gray-light-200 flex justify-center items-center p-7"],
  subContainer: ["w-0.7/2 bg-white rounded-md"],
  header: ["flex justify-between p-3"],
  team: ["font-semibold"],
  dropBox: ["text-[#212529] text-[12px] flex items-center"],
  hover: ["text-[#878A99] text-[13px] pl-1"],
  memberBox: ["w-full"],
  table: ["w-full text-left"],
  headerText: ["bg-[#f3f6f9]"],
  headerValue: ["p-2 text-[#878a99] text-sm"],
  tableImageBox: ["flex items-center space-x-2 p-3"],
  tableImage: ["flex items-center justify-center"],
  tableContent: [""],
  tableName: ["text-left text-[#495057] text-[13px] font-semibold"],
  tableRow: ["text-left text-[#878a99] text-[13px]"],
  tableProgress: [" flex items-center justify-center"],
  tableHour: ["text-sm pl-3 text-[#495057]"],
  tableStatus: ["text-sm pl-4 text-[#495057]"],
};
